using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieDB.Data;
using MovieDB.Models;
using MovieDB.Models.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace MovieDB.Controllers;

public class CompaniesController : Controller
{
    private readonly MovieDbContext dbContext;
    public CompaniesController(MovieDbContext dbContext) 
    {
        this.dbContext = dbContext;
    }

    private async Task PopulateMovieDropdownsAsync()
    {
        ViewBag.Movies = new SelectList(await dbContext.Movies.OrderBy(m => m.Title).ToListAsync(), "Awardable_ID", "Title");
    }
    
    [HttpGet]
    public IActionResult Add()
    {
        return View(new CompanyViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Add(CompanyViewModel model) 
    {
        if (ModelState.IsValid)
        {
            // ProductionCompany is not an Awardable, so no Awardable entity creation needed.
            
            var Company = new Company
                {
                    // Company_ID is auto-generated by the database
                    Name = model.Name, 
                    Country = model.Country,
                    Founded_Year = model.Founded_Year
                };
            
            await dbContext.Companies.AddAsync(Company); 
            await dbContext.SaveChangesAsync(); 
            TempData["SuccessMessage"] = "Production Company successfully added!"; 
            return RedirectToAction(nameof(List));
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> List()
    {
        var companies = await dbContext.Companies
            .Include(c => c.MovieCompanies)
                .ThenInclude(mc => mc.Movie)
            .ToListAsync(); 

        return View(companies);
    }
    
    // Details view might not be needed if List and Edit provide enough info.
    // If you want a Details view, it would be similar to Edit(Get).
    // For now, I'm omitting it to keep it concise, let me know if you need it.
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id) // id is Company_ID
    {
        var company = await dbContext.Companies
            .FirstOrDefaultAsync(c => c.Company_ID == id);

        if (company == null)
        {
            return NotFound();
        }

        var viewModel = new CompanyViewModel 
        {
            Company_ID = company.Company_ID,
            Name = company.Name, 
            Country = company.Country,
            Founded_Year = company.Founded_Year
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(CompanyViewModel model) 
    {
        if (ModelState.IsValid)
        {
            var company = await dbContext.Companies
                .FirstOrDefaultAsync(c => c.Company_ID == model.Company_ID);

            if (company == null)
            {
                return NotFound();
            }

            company.Name = model.Name; 
            company.Country = model.Country;
            company.Founded_Year = model.Founded_Year;
            
            await dbContext.SaveChangesAsync();
            TempData["SuccessMessage"] = "Production Company successfully updated!"; 
            return RedirectToAction(nameof(List));
        }
        return View(model);
    }
    
    // Delete Get action to show a confirmation view
    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var company = await dbContext.Companies
            .FirstOrDefaultAsync(c => c.Company_ID == id);

        if (company == null)
        {
            return NotFound();
        }
        // Pass the entity to the view for confirmation display
        return View(company); 
    }
    
    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var company = await dbContext.Companies
            .Include(c => c.MovieCompanies)
            .FirstOrDefaultAsync(c => c.Company_ID == id);

        if (company == null)
        {
            return NotFound();
        }

        // Explicitly remove the MovieCompany associations
        if (company.MovieCompanies != null && company.MovieCompanies.Any())
        {
            dbContext.MovieCompanies.RemoveRange(company.MovieCompanies);
        }

        dbContext.Companies.Remove(company); 

        await dbContext.SaveChangesAsync();

        TempData["SuccessMessage"] = "Production Company successfully deleted!"; 
        return RedirectToAction(nameof(List));
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id)
    {
        var company = await dbContext.Companies
            .Include(c => c.MovieCompanies)
                .ThenInclude(mc => mc.Movie)
            .FirstOrDefaultAsync(c => c.Company_ID == id);

        if (company == null)
        {
            return NotFound();
        }

        var viewModel = new CompanyViewModel
        {
            Company_ID = company.Company_ID,
            Name = company.Name,
            Country = company.Country,
            Founded_Year = company.Founded_Year,
            AssociatedMovies = company.MovieCompanies?.Select(mc => mc.Movie).ToList() ?? new List<Movie>()
        };

        await PopulateMovieDropdownsAsync();
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddMovieAssociation(int companyId, int movieId)
    {
        if (companyId <= 0 || movieId <= 0)
        {
            TempData["ErrorMessage"] = "Invalid company or movie ID.";
            return RedirectToAction(nameof(Details), new { id = companyId });
        }

        // Check if the association already exists
        var existingAssociation = await dbContext.MovieCompanies
            .AnyAsync(mc => mc.Company_ID == companyId && mc.Movie_ID == movieId);

        if (existingAssociation)
        {
            TempData["InfoMessage"] = "This movie is already associated with this company.";
            return RedirectToAction(nameof(Details), new { id = companyId });
        }

        // Create new association
        var newAssociation = new MovieCompany
        {
            Company_ID = companyId,
            Movie_ID = movieId
        };

        await dbContext.MovieCompanies.AddAsync(newAssociation);
        await dbContext.SaveChangesAsync();

        TempData["SuccessMessage"] = "Movie association added successfully.";
        return RedirectToAction(nameof(Details), new { id = companyId });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RemoveMovieAssociation(int companyId, int movieId)
    {
        var association = await dbContext.MovieCompanies
            .FirstOrDefaultAsync(mc => mc.Company_ID == companyId && mc.Movie_ID == movieId);

        if (association == null)
        {
            TempData["ErrorMessage"] = "Association not found.";
            return RedirectToAction(nameof(Details), new { id = companyId });
        }

        dbContext.MovieCompanies.Remove(association);
        await dbContext.SaveChangesAsync();

        TempData["SuccessMessage"] = "Movie association removed successfully.";
        return RedirectToAction(nameof(Details), new { id = companyId });
    }
}
